version: "3"
services:
  demo-app:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - .dockerenv:/src/.env
      - .:/src
    environment:
      - WATCHFILES_FORCE_POLLING=true
    shm_size: "2gb"
    init: true
  db:
    image: mysql:8.0
    platform: linux/x86_64
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
      MYSQL_DATABASE: demo
      TZ: "Asia/Tokyo"
    volumes:
      - mysql_data:/var/lib/mysql
    command: --default-authentication-plugin=mysql_native_password
    ports:
      - "33306:3306"
volumes:
  mysql_data:
